INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('bio-genetics-001', 'bio', 'พันธุศาสตร์และวิวัฒนาการ', 'การถ่ายทอดลักษณะ', '[]', 'hard', 'คำนวณสัดส่วนจีโนไทป์จากการผสมพันธุ์ 2 ลักษณะ (dihybrid cross) (ระดับค่าย สอวน)', NULL, 'mc5', 'ผสมพันธุ์พ่อแม่ที่มีจีโนไทป์ AaBb กับ AaBb โดยยีนทั้งสองคู่อยู่บนคนละโครโมโซม (independent assortment) ลูกที่ได้จะมีจีโนไทป์ aabb คิดเป็นสัดส่วนเท่าใด', '["1/4", "1/8", "1/16", "1/32", "3/16"]', '1/16', '["แต่ละคู่ยีนแยกกันอิสระ: โอกาสได้ aa = 1/4, โอกาสได้ bb = 1/4", "โอกาสได้ aabb พร้อมกัน = 1/4 × 1/4 = 1/16"]', '["ใช้อัตราส่วนฟีโนไทป์ 9:3:3:1 มาคำนวณโดยไม่แยกคิดทีละยีน"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('bio-hardyweinberg-001', 'bio', 'พันธุศาสตร์และวิวัฒนาการ', 'วิวัฒนาการ', '[]', 'hard', 'คำนวณสัดส่วนจีโนไทป์ด้วยหลักฮาร์ดี-ไวน์เบิร์ก (ระดับค่าย สอวน)', NULL, 'mc5', 'ประชากรหนึ่งอยู่ในสภาวะสมดุลฮาร์ดี-ไวน์เบิร์ก มีความถี่แอลลีลด้อย (q) เท่ากับ 0.2 สัดส่วนของประชากรที่มีจีโนไทป์เฮเทอโรไซกัส (พาหะ) เท่ากับเท่าใด', '["0.04", "0.16", "0.32", "0.64", "0.96"]', '0.32', '["p + q = 1 → p = 1-0.2 = 0.8", "สัดส่วนเฮเทอโรไซกัส = 2pq = 2×0.8×0.2 = 0.32"]', '["ลืมคูณ 2 ในสูตร 2pq หรือหาค่า p ผิดจาก q"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('bio-xlinked-001', 'bio', 'พันธุศาสตร์และวิวัฒนาการ', 'การถ่ายทอดลักษณะ', '[]', 'hard', 'วิเคราะห์การถ่ายทอดลักษณะแบบยีนด้อยบนโครโมโซม X (ระดับค่าย สอวน)', NULL, 'mc5', 'โรคพันธุกรรมชนิดหนึ่งถ่ายทอดแบบยีนด้อยบนโครโมโซม X พ่อมีจีโนไทป์ปกติ (XAY) แม่เป็นพาหะ (XAXa) ถ้ามีลูกชาย ลูกชายคนนั้นมีโอกาสเป็นโรคนี้เท่าใด', '["0", "1/4", "1/2", "3/4", "1"]', '1/2', '["ลูกชายได้ Y จากพ่อ และได้ X หนึ่งตัวจากแม่ (XA หรือ Xa อย่างละ 1/2)", "ลูกชายที่ได้ Xa จากแม่ (Xa Y) จะเป็นโรค ดังนั้นโอกาส = 1/2"]', '["คำนวณโอกาสจากลูกทุกคนแทนที่จะคิดเฉพาะในกลุ่มลูกชาย"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('bio-physio-001', 'bio', 'ระบบและการทำงานของสัตว์และมนุษย์', 'ระบบหมุนเวียนเลือด', '[]', 'hard', 'คำนวณปริมาณเลือดที่หัวใจสูบฉีดต่อนาที (cardiac output) (ระดับค่าย สอวน)', NULL, 'mc5', 'อัตราการเต้นของหัวใจเท่ากับ 72 ครั้งต่อนาที และปริมาตรเลือดที่บีบออกจากหัวใจต่อครั้ง (stroke volume) เท่ากับ 70 มิลลิลิตร ปริมาณเลือดที่หัวใจสูบฉีดต่อนาที (cardiac output) เท่ากับกี่ลิตรต่อนาที', '["4.0 ลิตร", "4.5 ลิตร", "5.0 ลิตร", "5.5 ลิตร", "6.0 ลิตร"]', '5.0 ลิตร', '["Cardiac output = อัตราการเต้นของหัวใจ × stroke volume", "= 72 × 70 = 5,040 มิลลิลิตร ≈ 5.0 ลิตรต่อนาที"]', '["ลืมแปลงหน่วยจากมิลลิลิตรเป็นลิตร"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('bio-ecology-001', 'bio', 'ความหลากหลายทางชีวภาพและสิ่งแวดล้อม', 'ระบบนิเวศและไบโอม', '[]', 'hard', 'คำนวณพลังงานที่ถ่ายทอดผ่านลำดับขั้นอาหารด้วยกฎ 10 เปอร์เซ็นต์ (ระดับค่าย สอวน)', NULL, 'mc5', 'พลังงานเริ่มต้นที่ผู้ผลิตในระบบนิเวศเท่ากับ 100,000 กิโลแคลอรี ถ้าการถ่ายทอดพลังงานระหว่างลำดับขั้นเป็นไปตามกฎ 10 เปอร์เซ็นต์ พลังงานที่ผู้บริโภคลำดับที่ 3 (tertiary consumer) ได้รับเท่ากับกี่กิโลแคลอรี', '["10", "100", "1,000", "10,000", "100,000"]', '100', '["ผู้บริโภคลำดับที่ 3 ผ่านการถ่ายทอดพลังงาน 3 ครั้งจากผู้ผลิต (ผู้ผลิต→ผู้บริโภคลำดับ1→ลำดับ2→ลำดับ3)", "พลังงาน = 100,000 × 0.1³ = 100 กิโลแคลอรี"]', '["นับจำนวนครั้งการถ่ายทอดพลังงานผิด (ใช้ 0.1² หรือ 0.1⁴ แทน)"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('bio-photosynthesis-001', 'bio', 'โครงสร้างและการทำงานของส่วนต่างๆ ในพืช', 'การสังเคราะห์ด้วยแสง', '[]', 'medium', 'ใช้อัตราส่วนสัดส่วนโมลจากสมการสังเคราะห์แสง (ระดับค่าย สอวน)', NULL, 'mc5', 'ปฏิกิริยาการสังเคราะห์ด้วยแสงโดยรวมคือ 6CO2 + 6H2O → C6H12O6 + 6O2 ถ้าพืชตรึงแก๊สคาร์บอนไดออกไซด์ 12 โมล จะปลดปล่อยแก๊สออกซิเจนกี่โมล', '["2 โมล", "6 โมล", "12 โมล", "18 โมล", "24 โมล"]', '12 โมล', '["จากสมการ อัตราส่วน CO2 ต่อ O2 = 6:6 = 1:1", "ถ้าใช้ CO2 12 โมล จะได้ O2 = 12 โมล"]', '["ใช้อัตราส่วนกับ C6H12O6 (6:1) แทนที่จะใช้อัตราส่วนกับ O2 (1:1)"]');
