INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-periodic-001', 'chem', 'สมบัติของธาตุและสารประกอบ', 'อะตอมและสมบัติของธาตุ', '[]', 'hard', 'ใช้แบบจำลองอะตอมของโบร์หาความยาวคลื่นของโฟตอนที่ปล่อยออกมา (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'อิเล็กตรอนในอะตอมไฮโดรเจนเปลี่ยนระดับพลังงานจาก n=3 ไปยัง n=2 ความยาวคลื่นของโฟตอนที่ปล่อยออกมาเท่ากับกี่นาโนเมตร (กำหนด R=1.097×10⁷ m⁻¹)', '["486 นาโนเมตร", "565 นาโนเมตร", "656 นาโนเมตร", "730 นาโนเมตร", "820 นาโนเมตร"]', '656 นาโนเมตร', '["ใช้สูตรริดเบิร์ก: 1/λ = R(1/n₂²-1/n₁²) = 1.097×10⁷×(1/4-1/9)", "1/λ = 1.097×10⁷×0.1389 = 1.524×10⁶ m⁻¹", "λ = 6.56×10⁻⁷ m = 656 นาโนเมตร"]', '["สลับตำแหน่ง n1 กับ n2 ในสูตรทำให้ได้ค่าติดลบ"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-bonding-001', 'chem', 'สมบัติของธาตุและสารประกอบ', 'พันธะเคมี', '[]', 'hard', 'คำนวณเอนทัลปีของปฏิกิริยาจากพลังงานพันธะ (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'ปฏิกิริยา H2(g)+Cl2(g)→2HCl(g) กำหนดพลังงานพันธะ H-H=436 kJ/mol, Cl-Cl=243 kJ/mol, H-Cl=431 kJ/mol เอนทัลปีของปฏิกิริยา (ΔH) เท่ากับเท่าใด', '["-183 kJ/mol", "-92 kJ/mol", "+92 kJ/mol", "+183 kJ/mol", "+431 kJ/mol"]', '-183 kJ/mol', '["ΔH = พลังงานพันธะที่สลาย - พลังงานพันธะที่เกิดขึ้น", "ΔH = (436+243) - 2(431) = 679-862 = -183 kJ/mol"]', '["ลืมคูณ 2 กับพันธะ H-Cl เพราะผลิตภัณฑ์มี HCl 2 โมเลกุล"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-organic-001', 'chem', 'สมบัติของธาตุและสารประกอบ', 'เคมีอินทรีย์', '[]', 'hard', 'คำนวณระดับขั้นความไม่อิ่มตัว (degree of unsaturation) จากสูตรโมเลกุล (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'สารประกอบชนิดหนึ่งมีสูตรโมเลกุล C6H10 ระดับขั้นความไม่อิ่มตัว (degree of unsaturation) เท่ากับเท่าใด', '["0", "1", "2", "3", "4"]', '2', '["ใช้สูตร DoU = (2C+2-H)/2 = (2×6+2-10)/2 = 4/2 = 2"]', '["ลืมบวก 2 ในสูตรก่อนลบด้วยจำนวน H"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-stoichiometry-001', 'chem', 'สมการเคมีและการเปลี่ยนแปลงทางเคมี', 'ปริมาณสัมพันธ์', '[]', 'hard', 'คำนวณร้อยละผลได้ (percent yield) ของปฏิกิริยา (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'สลาย CaCO3 มวล 10 กรัม ตามสมการ CaCO3→CaO+CO2 ได้ CaO จริง 5.04 กรัม ร้อยละผลได้ (percent yield) ของ CaO เท่ากับเท่าใด (มวลโมล CaCO3=100, CaO=56)', '["80%", "85%", "90%", "95%", "100%"]', '90%', '["โมล CaCO3 = 10/100 = 0.1 โมล → ผลได้ตามทฤษฎีของ CaO = 0.1×56 = 5.6 กรัม", "ร้อยละผลได้ = 5.04/5.6×100 = 90%"]', '["ลืมคำนวณผลได้ตามทฤษฎีก่อน นำมวลจริงไปเทียบกับมวลตั้งต้นโดยตรง"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-solution-001', 'chem', 'ทักษะปฏิบัติการเคมีและการคำนวณปริมาณสาร', 'สารละลาย', '[]', 'hard', 'คำนวณความเข้มข้นโมลาร์เมื่อผสมสารละลายสองความเข้มข้น (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'ผสมสารละลาย HCl เข้มข้น 0.6 โมลต่อลิตร ปริมาตร 100 มิลลิลิตร กับ HCl เข้มข้น 0.2 โมลต่อลิตร ปริมาตร 300 มิลลิลิตร ความเข้มข้นของสารละลายผสมสุดท้ายเท่ากับเท่าใด (ปริมาตรรวมกันได้พอดี)', '["0.2 M", "0.25 M", "0.3 M", "0.35 M", "0.4 M"]', '0.3 M', '["โมล HCl รวม = (0.1×0.6)+(0.3×0.2) = 0.06+0.06 = 0.12 โมล", "ปริมาตรรวม = 0.4 ลิตร → ความเข้มข้น = 0.12/0.4 = 0.3 M"]', '["ลืมแปลงหน่วยมิลลิลิตรเป็นลิตรก่อนคำนวณโมล"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-polymer-001', 'chem', 'สมบัติของธาตุและสารประกอบ', 'พอลิเมอร์', '[]', 'medium', 'คำนวณระดับขั้นการเกิดพอลิเมอร์ (degree of polymerization) (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'พอลิเอทิลีนชนิดหนึ่งมีมวลโมเลกุลเฉลี่ย 28,000 กรัมต่อโมล ถ้ามอนอเมอร์เอทิลีน (C2H4) มีมวลโมเลกุล 28 กรัมต่อโมล ระดับขั้นการเกิดพอลิเมอร์ (n) เท่ากับเท่าใด', '["100", "500", "1,000", "2,000", "5,000"]', '1,000', '["n = มวลโมเลกุลพอลิเมอร์/มวลโมเลกุลมอนอเมอร์ = 28,000/28 = 1,000"]', '["สลับตัวหารกับตัวตั้งในการหาร ทำให้ได้ค่า n ผิด"]');
