INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-logic-002', 'math1', 'จำนวนและพีชคณิต', 'ตรรกศาสตร์', '[]', 'medium', 'ใช้กฎการอ้างเหตุผลแบบ modus tollens', NULL, 'mc5', 'กำหนดข้อความ ''ถ้าฝนตก แล้วถนนเปียก'' เป็นจริง และทราบข้อเท็จจริงว่า ''ถนนไม่เปียก'' จากกฎ modus tollens สรุปได้ว่าข้อใดเป็นจริง', '["ฝนตก", "ฝนไม่ตก", "ถนนเปียก", "ไม่สามารถสรุปได้", "ฝนตกหรือถนนเปียก"]', 'ฝนไม่ตก', '["กฎ modus tollens: จาก p→q และ ~q สรุปได้ ~p", "p=''ฝนตก'', q=''ถนนเปียก'', ทราบ ~q (''ถนนไม่เปียก'') จึงสรุป ~p (''ฝนไม่ตก'')"]', '["สับสนกับ modus ponens ซึ่งต้องทราบ p ก่อนจึงสรุป q"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-poly-002', 'math1', 'จำนวนและพีชคณิต', 'จำนวนจริงและพหุนาม', '[]', 'hard', 'ใช้ทฤษฎีบทเศษเหลือและผลรวมราก (Vieta) หารากที่เหลือของพหุนาม', NULL, 'mc5', 'พหุนาม P(x)=x³-6x²+11x-6 มีรากหนึ่งคือ x=1 ผลรวมของรากอีกสองตัวที่เหลือเท่ากับเท่าใด', '["3", "4", "5", "6", "7"]', '5', '["ผลรวมของรากทั้งหมด = -(-6)/1 = 6 (จากทฤษฎีบทของเวียตา)", "ผลรวมของรากที่เหลือ = 6-1 = 5"]', '["ลืมใช้ทฤษฎีบทของเวียตา ไปพยายามแยกตัวประกอบทั้งหมดโดยไม่จำเป็น"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-explog-002', 'math1', 'จำนวนและพีชคณิต', 'เอกซ์โพเนนเชียลและลอการิทึม', '[]', 'hard', 'แก้สมการลอการิทึมพร้อมตรวจสอบโดเมน', NULL, 'mc5', 'จงหาค่า x จากสมการ log₂(x) + log₂(x-2) = 3', '["-2", "2", "4", "6", "8"]', '4', '["รวมลอการิทึม: log₂(x(x-2))=3 → x(x-2)=8 → x²-2x-8=0", "แยกตัวประกอบ: (x-4)(x+2)=0 → x=4 หรือ x=-2", "ตรวจโดเมน (x>0 และ x-2>0 คือ x>2) เหลือคำตอบเดียวคือ x=4"]', '["ลืมตรวจโดเมน ตอบ x=-2 ซึ่งทำให้ log ของค่าลบซึ่งไม่นิยาม"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-trig-002', 'math1', 'จำนวนและพีชคณิต', 'ฟังก์ชันตรีโกณมิติ', '[]', 'hard', 'แก้สมการตรีโกณมิติหาคำตอบทั้งหมดในช่วงที่กำหนด', NULL, 'mc5', 'ในช่วง [0°,360°) ผลรวมของค่า x ทั้งหมดที่สอดคล้องกับสมการ 2sin(x)-1=0 เท่ากับเท่าใด', '["30°", "60°", "150°", "180°", "210°"]', '180°', '["2sin(x)-1=0 → sin(x)=1/2", "คำตอบในช่วง [0°,360°) คือ x=30° และ x=150°", "ผลรวม = 30+150 = 180°"]', '["หาคำตอบได้แค่ค่าเดียว (30°) โดยลืมว่า sine เป็นบวกในควอดรันต์ที่ 2 ด้วย"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-complex-002', 'math1', 'จำนวนและพีชคณิต', 'จำนวนเชิงซ้อน', '[]', 'hard', 'ใช้รูปเชิงขั้วหรือการยกกำลังจำนวนเชิงซ้อน', NULL, 'mc5', 'จงหาค่าของ (1+i)⁴ ในรูป a+bi', '["-4", "4", "-4i", "4i", "-4+4i"]', '-4', '["(1+i)² = 1+2i+i² = 2i", "(1+i)⁴ = (2i)² = 4i² = -4"]', '["ยกกำลังทีละพจน์แยกส่วนจริงกับส่วนจินตภาพโดยไม่ขยายทวินามให้ถูกต้อง"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-seq-002', 'math1', 'จำนวนและพีชคณิต', 'ลำดับและอนุกรม', '[]', 'medium', 'ใช้ลำดับเรขาคณิตกับดอกเบี้ยทบต้น', NULL, 'mc5', 'ฝากเงิน 1,000 บาท ได้ดอกเบี้ยทบต้นปีละ 10% ทุกปี (ไม่ถอนออก) เมื่อครบ 3 ปี จะมีเงินทั้งหมดเท่าใด', '["1,100 บาท", "1,210 บาท", "1,300 บาท", "1,331 บาท", "1,400 บาท"]', '1,331 บาท', '["ใช้สูตรดอกเบี้ยทบต้น: A = P(1+r)ⁿ = 1000×(1.1)³", "= 1000×1.331 = 1,331 บาท"]', '["คำนวณดอกเบี้ยแบบไม่ทบต้น (1000+3×100=1300) แทนที่จะทบต้นจริง"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-geo-002', 'math1', 'การวัดและเรขาคณิต', 'เรขาคณิตวิเคราะห์', '[]', 'medium', 'หาระยะห่างจากจุดถึงเส้นตรง', NULL, 'mc5', 'จงหาระยะห่างจากจุด (3,4) ถึงเส้นตรง 3x+4y-10=0', '["1", "2", "3", "4", "5"]', '3', '["ใช้สูตรระยะห่างจากจุดถึงเส้นตรง: d = |Ax₀+By₀+C|/√(A²+B²)", "d = |3(3)+4(4)-10|/√(9+16) = |15|/5 = 3"]', '["ลืมใส่ค่าสัมบูรณ์ก่อนหารด้วยรากที่สองของผลรวมกำลังสองสัมประสิทธิ์"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-vec-002', 'math1', 'การวัดและเรขาคณิต', 'เวกเตอร์ในสามมิติ', '[]', 'hard', 'หามุมระหว่างเวกเตอร์ด้วยผลคูณเชิงสเกลาร์', NULL, 'mc5', 'กำหนดเวกเตอร์ u=(2,2,1) และ v=(1,-2,2) มุมระหว่างเวกเตอร์ทั้งสองเท่ากับเท่าใด', '["0°", "30°", "45°", "60°", "90°"]', '90°', '["u·v = 2(1)+2(-2)+1(2) = 2-4+2 = 0", "เมื่อผลคูณเชิงสเกลาร์เป็น 0 แสดงว่าเวกเตอร์ตั้งฉากกัน (มุม 90°)"]', '["คำนวณผลคูณเชิงสเกลาร์ผิดเครื่องหมายทำให้ไม่ได้ค่า 0"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-probdist-002', 'math1', 'สถิติและความน่าจะเป็น', 'การแจกแจงความน่าจะเป็นเบื้องต้น', '[]', 'medium', 'คำนวณค่ามาตรฐาน (Z-score) จากการแจกแจงปกติ', NULL, 'mc5', 'คะแนนสอบมีการแจกแจงปกติ ค่าเฉลี่ย 70 คะแนน ส่วนเบี่ยงเบนมาตรฐาน 10 คะแนน นักเรียนคนหนึ่งได้ 85 คะแนน มีค่ามาตรฐาน (Z-score) เท่าใด', '["0.5", "1.0", "1.5", "2.0", "2.5"]', '1.5', '["Z = (X-μ)/σ = (85-70)/10 = 1.5"]', '["ลืมหารด้วยส่วนเบี่ยงเบนมาตรฐาน ใช้แค่ผลต่างของคะแนน"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-count-002', 'math1', 'สถิติและความน่าจะเป็น', 'หลักการนับเบื้องต้น', '[]', 'hard', 'การเรียงสับเปลี่ยนแบบมีเงื่อนไข (จัดกลุ่มติดกัน)', NULL, 'mc5', 'มีหนังสือ 5 เล่มต่างกัน ต้องการจัดเรียงบนชั้นเป็นแถว โดยให้หนังสือ 2 เล่มที่กำหนดไว้อยู่ติดกันเสมอ มีวิธีจัดเรียงได้กี่วิธี', '["24", "36", "48", "60", "120"]', '48', '["มัดหนังสือ 2 เล่มที่ต้องติดกันเป็น 1 ก้อน เหลือ 4 หน่วยให้จัดเรียง = 4! วิธี", "ภายในก้อนสลับตำแหน่งกันได้ 2! วิธี", "รวม = 4!×2! = 24×2 = 48 วิธี"]', '["ลืมคูณด้วย 2! สำหรับการสลับตำแหน่งภายในก้อนที่ติดกัน"]');
