INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('phy-measurement-001', 'phy', 'กลศาสตร์', 'ธรรมชาติและพัฒนาการทางฟิสิกส์', '[]', 'medium', 'ใช้กฎเลขนัยสำคัญในการคำนวณ (ระดับค่าย สอวน)', NULL, 'mc5', 'ผลคูณ 12.34 × 2.1 เมื่อคำนึงถึงกฎเลขนัยสำคัญ ควรรายงานผลลัพธ์เป็นเท่าใด', '["25", "25.9", "26", "25.91", "26.0"]', '26', '["12.34 มี 4 เลขนัยสำคัญ, 2.1 มี 2 เลขนัยสำคัญ", "ผลคูณต้องมีเลขนัยสำคัญเท่ากับตัวที่น้อยที่สุด (2 ตัว)", "12.34×2.1=25.914 ปัดเหลือ 2 เลขนัยสำคัญ = 26"]', '["รายงานผลลัพธ์ด้วยจำนวนหลักทศนิยมทั้งหมดโดยไม่ปัดตามเลขนัยสำคัญที่น้อยที่สุด"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('phy-equilibrium-001', 'phy', 'กลศาสตร์', 'สมดุลกล', '[]', 'hard', 'ใช้หลักสมดุลของโมเมนต์ (torque balance) กับคานหมุน (ระดับค่าย สอวน)', NULL, 'mc5', 'คานสม่ำเสมอยาว 4 เมตร วางบนจุดหมุนตรงกลาง แขวนน้ำหนัก 50 นิวตัน ที่ระยะ 1.5 เมตรจากจุดหมุนด้านซ้าย ต้องแขวนน้ำหนัก 30 นิวตันที่ระยะเท่าใดจากจุดหมุนด้านขวา คานจึงจะสมดุล', '["1.5 เมตร", "2.0 เมตร", "2.5 เมตร", "3.0 เมตร", "3.5 เมตร"]', '2.5 เมตร', '["สมดุลโมเมนต์: โมเมนต์ซ้าย = โมเมนต์ขวา", "50×1.5 = 30×d → d = 75/30 = 2.5 เมตร"]', '["ลืมว่าโมเมนต์ต้องเท่ากันทั้งสองข้างของจุดหมุน ไปบวกแรงตรงๆ แทน"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('phy-magnetism-001', 'phy', 'ไฟฟ้า แม่เหล็ก และคลื่นแม่เหล็กไฟฟ้า', 'แม่เหล็กและไฟฟ้า', '[]', 'medium', 'คำนวณแรงบนลวดตัวนำในสนามแม่เหล็ก (F=BIL) (ระดับค่าย สอวน)', NULL, 'mc5', 'ลวดตัวนำยาว 0.4 เมตร มีกระแสไฟฟ้าไหลผ่าน 5 แอมแปร์ วางในสนามแม่เหล็กขนาด 0.2 เทสลา ในทิศตั้งฉากกับลวด แรงที่กระทำต่อลวดเท่ากับกี่นิวตัน', '["0.1", "0.2", "0.4", "0.8", "1.0"]', '0.4', '["F = BIL = 0.2×5×0.4 = 0.4 นิวตัน"]', '["ลืมคูณความยาวของลวด ใช้แค่ F=BI"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('phy-emwave-001', 'phy', 'ไฟฟ้า แม่เหล็ก และคลื่นแม่เหล็กไฟฟ้า', 'คลื่นแม่เหล็กไฟฟ้า', '[]', 'medium', 'ใช้ความสัมพันธ์ระหว่างความถี่และความยาวคลื่นแม่เหล็กไฟฟ้า (ระดับค่าย สอวน)', NULL, 'mc5', 'คลื่นวิทยุความถี่ 100 เมกะเฮิรตซ์ มีความยาวคลื่นเท่ากับกี่เมตร (กำหนด c=3×10⁸ m/s)', '["1", "2", "3", "4", "5"]', '3', '["λ = c/f = (3×10⁸)/(100×10⁶) = 3 เมตร"]', '["ลืมแปลงหน่วยเมกะเฮิรตซ์เป็นเฮิรตซ์ก่อนคำนวณ"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('phy-light-001', 'phy', 'คลื่นกล และแสง', 'แสง', '[]', 'hard', 'ใช้กฎการหักเหของสเนลล์ (Snell''s law) (ระดับค่าย สอวน)', NULL, 'mc5', 'แสงเดินทางจากอากาศ (n=1) เข้าสู่แก้ว (n=1.5) ทำมุมตกกระทบ 30° มุมหักเหในแก้วมีค่าประมาณเท่าใด', '["15°", "19.5°", "25°", "30°", "45°"]', '19.5°', '["ใช้กฎของสเนลล์: n₁sin(θ₁) = n₂sin(θ₂)", "sin(θ₂) = (1×sin30°)/1.5 = 0.5/1.5 = 0.333", "θ₂ = arcsin(0.333) ≈ 19.5°"]', '["สลับตำแหน่ง n1 กับ n2 ในสมการทำให้มุมหักเหมากกว่ามุมตกกระทบผิดทิศทาง"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('phy-fluid-001', 'phy', 'อุณหพลศาสตร์และสมบัติเชิงกลของสาร', 'ของแข็งและของไหล', '[]', 'medium', 'ใช้หลักของอาร์คิมิดีสหามวลวัตถุที่ลอยน้ำ (ระดับค่าย สอวน)', NULL, 'mc5', 'วัตถุก้อนหนึ่งปริมาตร 0.002 ลูกบาศก์เมตร ลอยอยู่ในน้ำ (ความหนาแน่นน้ำ=1000 กก./ลบ.ม.) โดยจมอยู่ใต้น้ำ 60% ของปริมาตร มวลของวัตถุนี้เท่ากับกี่กิโลกรัม', '["0.8", "1.0", "1.2", "1.5", "2.0"]', '1.2', '["ปริมาตรที่จมน้ำ = 0.6×0.002 = 0.0012 ลบ.ม.", "จากสมดุลการลอย มวลวัตถุ = ความหนาแน่นน้ำ×ปริมาตรที่จม = 1000×0.0012 = 1.2 กิโลกรัม"]', '["ใช้ปริมาตรทั้งหมดของวัตถุแทนที่จะใช้เฉพาะส่วนที่จมน้ำ"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('phy-nuclear-001', 'phy', 'ฟิสิกส์แผนใหม่', 'ฟิสิกส์นิวเคลียร์และอนุภาค', '[]', 'medium', 'คำนวณมวลคงเหลือจากครึ่งชีวิตของสารกัมมันตรังสี (ระดับค่าย สอวน)', NULL, 'mc5', 'สารกัมมันตรังสีชนิดหนึ่งมีครึ่งชีวิต 10 วัน เริ่มต้นมีมวล 80 กรัม หลังจากผ่านไป 30 วัน จะเหลือมวลเท่าใด', '["5 กรัม", "10 กรัม", "20 กรัม", "26.7 กรัม", "40 กรัม"]', '10 กรัม', '["30 วัน = 3 ครึ่งชีวิต (30/10=3)", "มวลคงเหลือ = 80×(1/2)³ = 80/8 = 10 กรัม"]', '["หารมวลตั้งต้นด้วยจำนวนวันโดยตรงแทนที่จะยกกำลังตามจำนวนครึ่งชีวิต"]');
