INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-mole-001', 'chem', 'ทักษะปฏิบัติการเคมีและการคำนวณปริมาณสาร', 'โมล', '[]', 'hard', 'หาสารกำหนดปริมาณ (limiting reagent) แล้วคำนวณมวลผลิตภัณฑ์ (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'แก๊สไนโตรเจน 2 โมล ทำปฏิกิริยากับแก๊สไฮโดรเจน 3 โมล ตามสมการ N2 + 3H2 → 2NH3 มวลของแอมโมเนียที่ผลิตได้มากที่สุดเท่ากับกี่กรัม (มวลอะตอม N=14, H=1)', '["17 กรัม", "34 กรัม", "51 กรัม", "68 กรัม", "102 กรัม"]', '34 กรัม', '["เช็คสารกำหนดปริมาณ: N2 2 โมล ต้องการ H2 = 2×3 = 6 โมล แต่มีเพียง 3 โมล ดังนั้น H2 เป็นสารกำหนดปริมาณ", "จาก H2 3 โมล ผลิต NH3 = 3×(2/3) = 2 โมล", "มวล NH3 = 2×17 = 34 กรัม"]', '["ใช้ N2 เป็นฐานคำนวณโดยไม่เช็คว่าเป็นสารกำหนดปริมาณหรือไม่"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-gas-001', 'chem', 'สมบัติของธาตุและสารประกอบ', 'แก๊ส', '[]', 'hard', 'ใช้กฎรวมแก๊ส (combined gas law) (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'แก๊สอุดมคติปริมาตร 4 ลิตร ที่ความดัน 2 บรรยากาศ อุณหภูมิ 300 เคลวิน ถ้าเปลี่ยนสภาวะเป็นความดัน 1 บรรยากาศ อุณหภูมิ 450 เคลวิน ปริมาตรของแก๊สจะเป็นเท่าใด', '["6 ลิตร", "8 ลิตร", "10 ลิตร", "12 ลิตร", "16 ลิตร"]', '12 ลิตร', '["ใช้กฎรวมแก๊ส P1V1/T1 = P2V2/T2", "V2 = P1V1T2/(T1P2) = (2×4×450)/(300×1) = 12 ลิตร"]', '["ลืมแปลงหน่วยอุณหภูมิเป็นเคลวิน หรือสลับตำแหน่งตัวแปรในสูตร"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-rate-001', 'chem', 'สมการเคมีและการเปลี่ยนแปลงทางเคมี', 'อัตราการเกิดปฏิกิริยา', '[]', 'hard', 'หาอันดับปฏิกิริยาจากข้อมูลการทดลอง (ระดับค่าย สอวน)', 'data_interpretation', 'mc5', 'จากการทดลองปฏิกิริยา A+B→ผลิตภัณฑ์ พบข้อมูล 3 การทดลอง: (1) [A]=0.1, [B]=0.1, อัตรา=0.02 (2) [A]=0.2, [B]=0.1, อัตรา=0.08 (3) [A]=0.1, [B]=0.2, อัตรา=0.04 อันดับปฏิกิริยารวม (overall order) เท่ากับเท่าใด', '["1", "2", "3", "4", "5"]', '3', '["เทียบการทดลอง 1 กับ 2 (เพิ่ม [A] เป็น 2 เท่า อัตราเพิ่ม 4 เท่า): 2^m=4 → m=2 (อันดับใน A)", "เทียบการทดลอง 1 กับ 3 (เพิ่ม [B] เป็น 2 เท่า อัตราเพิ่ม 2 เท่า): 2^n=2 → n=1 (อันดับใน B)", "อันดับรวม = m+n = 2+1 = 3"]', '["ลืมเทียบเฉพาะคู่ทดลองที่เปลี่ยนความเข้มข้นทีละตัว"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-equilibrium-001', 'chem', 'สมการเคมีและการเปลี่ยนแปลงทางเคมี', 'สมดุลเคมี', '[]', 'hard', 'คำนวณค่าคงที่สมดุล Kc ด้วยตาราง ICE (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'ปฏิกิริยา H2(g) + I2(g) ⇌ 2HI(g) เริ่มต้นมี H2 และ I2 อย่างละ 1.0 โมลต่อลิตร ไม่มี HI เมื่อเข้าสู่สมดุลพบว่ามี HI เกิดขึ้น 1.6 โมลต่อลิตร ค่าคงที่สมดุล Kc ของปฏิกิริยานี้เท่ากับเท่าใด', '["16", "32", "48", "64", "80"]', '64', '["จากอัตราส่วนสมการ HI ที่เกิด 1.6 โมล ใช้ H2 และ I2 ไปอย่างละ 1.6/2=0.8 โมล", "ที่สมดุล: [H2]=[I2]=1-0.8=0.2, [HI]=1.6", "Kc = [HI]²/([H2][I2]) = 1.6²/(0.2×0.2) = 2.56/0.04 = 64"]', '["ลืมหารด้วย 2 ตอนหาปริมาณ H2 และ I2 ที่ทำปฏิกิริยาไปจากสัดส่วนโมล"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-acidbase-001', 'chem', 'สมการเคมีและการเปลี่ยนแปลงทางเคมี', 'กรด-เบส', '[]', 'hard', 'คำนวณ pH ของกรดอ่อนจากค่า Ka (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'กรดอ่อน HA เข้มข้น 0.1 โมลต่อลิตร มีค่าคงที่การแตกตัว Ka = 1.0×10⁻⁵ pH ของสารละลายนี้มีค่าประมาณเท่าใด', '["1", "2", "3", "4", "5"]', '3', '["ประมาณ [H+] ≈ √(Ka×C) = √(1.0×10⁻⁵ × 0.1) = √(1.0×10⁻⁶) = 1.0×10⁻³ โมลต่อลิตร", "pH = -log(1.0×10⁻³) = 3"]', '["ลืมถอดรากที่สองก่อนหา pH หรือคำนวณ log ผิดเครื่องหมาย"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('chem-electrochem-001', 'chem', 'สมการเคมีและการเปลี่ยนแปลงทางเคมี', 'เคมีไฟฟ้า', '[]', 'hard', 'คำนวณศักย์ไฟฟ้ามาตรฐานของเซลล์กัลวานิก (ระดับค่าย สอวน)', 'quantitative', 'mc5', 'เซลล์กัลวานิกประกอบด้วยขั้ว Zn (E°=-0.76 V) เป็นแอโนด และขั้ว Cu (E°=+0.34 V) เป็นแคโทด ค่าศักย์ไฟฟ้ามาตรฐานของเซลล์ (E°cell) เท่ากับเท่าใด', '["-1.10 V", "-0.42 V", "+0.42 V", "+1.10 V", "+1.42 V"]', '+1.10 V', '["E°cell = E°cathode - E°anode", "E°cell = 0.34 - (-0.76) = 1.10 V"]', '["สลับค่า cathode กับ anode หรือลืมเครื่องหมายลบของ E° ของ Zn"]');
