INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-set-001', 'math1', 'จำนวนและพีชคณิต', 'เซต', '[]', 'medium', 'ใช้สูตรยูเนียนของสองเซตจากข้อมูลสำรวจ', 'mc5', 'จากการสำรวจนักเรียน 50 คน พบว่าชอบดื่มชา 28 คน ชอบดื่มกาแฟ 22 คน และมี 10 คนที่ไม่ชอบดื่มทั้งสองอย่างเลย มีนักเรียนกี่คนที่ชอบดื่มทั้งชาและกาแฟ', '["6", "8", "10", "12", "14"]', '10', '["ชอบอย่างน้อย 1 อย่าง = 50-10 = 40 คน", "จาก |T∪C|=|T|+|C|-|T∩C| → 40=28+22-x → x=10"]', '["ลืมหักคนที่ไม่ชอบทั้งสองอย่างออกก่อนใช้สูตร"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-log-001', 'math1', 'จำนวนและพีชคณิต', 'ตรรกศาสตร์', '[]', 'medium', 'หาข้อความสมมูลด้วย contrapositive', 'mc5', 'กำหนด p แทน ''ฝนตก'' และ q แทน ''ฉันพกร่ม'' ข้อความ ''ถ้าฝนไม่ตก แล้วฉันจะไม่พกร่ม'' สมมูลกับข้อความในข้อใด', '["ถ้าฝนตก แล้วฉันพกร่ม", "ถ้าฉันพกร่ม แล้วฝนตก", "ถ้าฉันไม่พกร่ม แล้วฝนไม่ตก", "ฝนตกและฉันพกร่ม", "ฝนไม่ตกหรือฉันไม่พกร่ม"]', 'ถ้าฉันพกร่ม แล้วฝนตก', '["ข้อความเดิมอยู่ในรูป ~p→~q", "สมมูลกับ contrapositive คือ q→p"]', '["สับสนระหว่างบทกลับ (converse) กับ contrapositive"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-poly-001', 'math1', 'จำนวนและพีชคณิต', 'จำนวนจริงและพหุนาม', '[]', 'easy', 'ตั้งอสมการจากเงื่อนไขต้นทุน-กำไร', 'mc5', 'ร้านขายเสื้อได้กำไรตัวละ 150 บาท และมีค่าใช้จ่ายคงที่วันละ 3,000 บาท ร้านต้องขายเสื้ออย่างน้อยกี่ตัวต่อวันจึงจะไม่ขาดทุน', '["15", "18", "20", "22", "25"]', '20', '["ตั้งอสมการ 150x-3000≥0", "แก้ได้ x≥20"]', '["ลืมใส่เครื่องหมายเท่ากับ (ไม่ขาดทุน = กำไรอย่างน้อย 0)"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-fn-001', 'math1', 'จำนวนและพีชคณิต', 'ฟังก์ชัน', '["แคลคูลัส"]', 'hard', 'แปลงเงื่อนไขจริงเป็นฟังก์ชันกำลังสองแล้วหาค่าสูงสุด', 'mc5', 'กำไรต่อวัน P(x) บาท ของร้านเบเกอรี่เมื่อขายเค้ก x ชิ้น เป็นฟังก์ชันพหุนามกำลังสอง โดยวันที่ไม่ขายเลยขาดทุน 100 บาท ส่วนวันที่ขาย 10 ชิ้น และ 30 ชิ้น มีกำไรเท่ากันคือ 200 บาท ร้านนี้จะมีกำไรสูงสุดต่อวันเท่าไร', '["250 บาท", "275 บาท", "300 บาท", "325 บาท", "350 บาท"]', '300 บาท', '["ตั้ง P(x)=ax²+bx+c จาก 3 เงื่อนไข", "แก้ระบบสมการได้ P(x)=-x²+40x-100", "จุดสูงสุดอยู่ที่ x=20 ได้ P(20)=300 บาท"]', '["ตั้งสมการจากเงื่อนไขผิดคู่ ทำให้แก้ระบบไม่ตรง"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-explog-001', 'math1', 'จำนวนและพีชคณิต', 'เอกซ์โพเนนเชียลและลอการิทึม', '[]', 'medium', 'การเติบโตแบบทวีคูณ (exponential growth)', 'mc5', 'แบคทีเรียชนิดหนึ่งเพิ่มเป็น 2 เท่าทุก 3 ชั่วโมง เริ่มต้นมี 500 ตัว อีกกี่ชั่วโมงจึงจะมีครบ 4,000 ตัว', '["6", "9", "12", "15", "18"]', '9', '["4000/500=8=2³", "ต้องเพิ่มเป็น 2 เท่า 3 รอบ รอบละ 3 ชม.", "รวม 9 ชั่วโมง"]', '["คูณ 3 ชม. กับ 8 เท่าตรงๆ แทนที่จะแปลงเป็นเลขชี้กำลังก่อน"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-trig-001', 'math1', 'จำนวนและพีชคณิต', 'ฟังก์ชันตรีโกณมิติ', '[]', 'easy', 'ใช้มุมเงยหาความสูง', 'mc5', 'ชายคนหนึ่งยืนห่างจากตึกแห่งหนึ่ง 30 เมตร มองยอดตึกเป็นมุมเงย 60° ตึกนี้สูงกี่เมตร (tan60°=√3)', '["15√3", "20√3", "30√3", "30√2", "60"]', '30√3', '["ความสูง = 30×tan60° = 30√3 เมตร"]', '["ใช้ sin หรือ cos แทน tan ในโจทย์มุมเงย"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-complex-001', 'math1', 'จำนวนและพีชคณิต', 'จำนวนเชิงซ้อน', '[]', 'easy', 'การคูณจำนวนเชิงซ้อน', 'mc5', 'กำหนด z₁ = 2+3i และ z₂ = 1-2i จงหาค่าของ z₁·z₂', '["8 - i", "8 + i", "-1 - i", "-4 - i", "4 - i"]', '8 - i', '["(2+3i)(1-2i)=2-4i+3i-6i²", "=2-i+6=8-i (เพราะ i²=-1)"]', '["ลืมว่า i²=-1 ทำให้บวกลบเครื่องหมายผิด"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-matrix-001', 'math1', 'จำนวนและพีชคณิต', 'เมทริกซ์', '[]', 'medium', 'แก้ระบบสมการเชิงเส้น 2 ตัวแปรจากสถานการณ์จริง', 'mc5', 'ร้านขายผลไม้ วันแรกขายส้ม 2 กก. และแอปเปิ้ล 3 กก. ได้เงินรวม 220 บาท วันที่สองขายส้ม 4 กก. และแอปเปิ้ล 1 กก. ได้เงินรวม 140 บาท ส้มราคากิโลกรัมละกี่บาท (แก้ระบบสมการด้วยเมทริกซ์)', '["15", "20", "25", "30", "35"]', '20', '["ตั้ง 2x+3y=220 และ 4x+y=140", "แก้ระบบสมการได้ x=20 (ส้ม), y=60 (แอปเปิ้ล)"]', '["สลับตัวแปร x,y ระหว่างส้มกับแอปเปิ้ล"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-seq-001', 'math1', 'จำนวนและพีชคณิต', 'ลำดับและอนุกรม', '[]', 'medium', 'ผลบวกอนุกรมเลขคณิต', 'mc5', 'นายเอฝากเงินเดือนแรก 500 บาท และฝากเพิ่มเดือนละ 100 บาทจากเดือนก่อนหน้าไปเรื่อยๆ (ไม่มีดอกเบี้ย) ครบ 12 เดือน จะมีเงินฝากสะสมทั้งหมดกี่บาท', '["10,800", "11,700", "12,600", "13,200", "14,400"]', '12,600', '["เป็นลำดับเลขคณิต a₁=500, d=100, n=12", "Sn=n/2[2a₁+(n-1)d]=6[1000+1100]=12,600 บาท"]', '["ใช้สูตรผลบวกลำดับเรขาคณิตแทนเลขคณิต"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-geo-001', 'math1', 'การวัดและเรขาคณิต', 'เรขาคณิตวิเคราะห์', '[]', 'easy', 'สูตรระยะห่างระหว่างจุด', 'mc5', 'บนแผนที่พิกัดหน่วยกิโลเมตร ร้านกาแฟอยู่ที่ (2,3) และบ้านของนายบีอยู่ที่ (6,6) บ้านของนายบีอยู่ห่างจากร้านกาแฟกี่กิโลเมตร', '["4", "5", "6", "7", "8"]', '5', '["ระยะทาง=√((6-2)²+(6-3)²)=√25=5 กิโลเมตร"]', '["ลืมถอดรากที่สองตอนท้าย"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-vec-001', 'math1', 'การวัดและเรขาคณิต', 'เวกเตอร์ในสามมิติ', '[]', 'easy', 'ขนาดของเวกเตอร์ 3 มิติ', 'mc5', 'แรงที่กระทำต่อวัตถุชิ้นหนึ่งแทนด้วยเวกเตอร์ u = (1,2,2) หน่วยนิวตัน ขนาดของแรงนี้เท่ากับกี่นิวตัน', '["2", "3", "4", "5", "6"]', '3', '["|u|=√(1²+2²+2²)=√9=3 นิวตัน"]', '["ลืมยกกำลังสองก่อนบวกแล้วถอดราก"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-stat-001', 'math1', 'สถิติและความน่าจะเป็น', 'สถิติ', '[]', 'easy', 'ค่าเฉลี่ยเลขคณิต', 'mc5', 'คะแนนสอบของนักเรียน 5 คน คือ 60, 70, 75, 80, 90 ค่าเฉลี่ยเลขคณิตของคะแนนชุดนี้เท่ากับเท่าใด', '["70", "72", "75", "78", "80"]', '75', '["ค่าเฉลี่ย=(60+70+75+80+90)/5=375/5=75"]', '["หารด้วยจำนวนข้อมูลผิด"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-prob-dist-001', 'math1', 'สถิติและความน่าจะเป็น', 'การแจกแจงความน่าจะเป็นเบื้องต้น', '[]', 'hard', 'การแจกแจงทวินาม', 'mc5', 'โรงงานผลิตหลอดไฟ มีโอกาสเป็นหลอดเสีย 10% สุ่มหลอดไฟมา 3 หลอด ความน่าจะเป็นที่จะได้หลอดเสียพอดี 1 หลอด เท่ากับเท่าใด', '["0.081", "0.243", "0.27", "0.343", "0.729"]', '0.243', '["ใช้สูตรทวินาม C(3,1)(0.1)¹(0.9)²", "=3×0.1×0.81=0.243"]', '["ลืมคูณด้วย C(3,1)"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-count-001', 'math1', 'สถิติและความน่าจะเป็น', 'หลักการนับเบื้องต้น', '[]', 'medium', 'การจัดหมู่ (combination)', 'mc5', 'ร้านอาหารมีเมนู 5 ชนิด ลูกค้าต้องการเลือกอาหาร 2 ชนิดจาก 5 ชนิดนี้มารับประทาน (ไม่สนลำดับ) มีวิธีเลือกได้กี่วิธี', '["8", "9", "10", "12", "15"]', '10', '["ไม่สนลำดับ ใช้การจัดหมู่ C(5,2)", "C(5,2)=10 วิธี"]', '["ใช้การเรียงสับเปลี่ยน (permutation) แทนการจัดหมู่"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-prob-001', 'math1', 'สถิติและความน่าจะเป็น', 'ความน่าจะเป็น', '[]', 'easy', 'ความน่าจะเป็นพื้นฐาน', 'mc5', 'กล่องใบหนึ่งมีลูกบอลสีแดง 4 ลูก และสีน้ำเงิน 6 ลูก สุ่มหยิบลูกบอล 1 ลูก ความน่าจะเป็นที่จะได้ลูกบอลสีแดงเท่ากับเท่าใด', '["1/5", "2/5", "1/2", "3/5", "4/5"]', '2/5', '["P(แดง)=4/10=2/5"]', '["ลืมลดเศษส่วนให้เป็นเศษส่วนอย่างต่ำ"]');
INSERT INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-calc-001', 'math1', 'แคลคูลัส', 'แคลคูลัสเบื้องต้น', '[]', 'medium', 'หาจุดต่ำสุดด้วยอนุพันธ์', 'mc5', 'ต้นทุนรวมในการผลิตสินค้า x ชิ้น คือ C(x) = x²-40x+500 (บาท) จำนวนการผลิตที่ทำให้ต้นทุนต่ำที่สุดคือกี่ชิ้น', '["15", "18", "20", "22", "25"]', '20', '["หาอนุพันธ์ C''(x)=2x-40", "ให้ C''(x)=0 → x=20 ชิ้น"]', '["ลืมตรวจว่าเป็นจุดต่ำสุด (a>0) ไม่ใช่จุดสูงสุด"]');
