INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-set-002', 'math1', 'จำนวนและพีชคณิต', 'เซต', '[]', 'hard', 'ใช้หลักการเพิ่มเข้า-ตัดออก (inclusion-exclusion) กับ 3 เซต', NULL, 'mc5', 'จากการสำรวจนักเรียน 150 คน พบว่าชอบฟุตบอล 70 คน บาสเกตบอล 60 คน วอลเลย์บอล 50 คน ชอบทั้งฟุตบอลและบาสเกตบอล 20 คน ชอบทั้งบาสเกตบอลและวอลเลย์บอล 15 คน ชอบทั้งฟุตบอลและวอลเลย์บอล 10 คน และชอบทั้งสามอย่าง 5 คน มีนักเรียนกี่คนที่ไม่ชอบกีฬาใดเลยในสามชนิดนี้', '["5", "8", "10", "12", "15"]', '10', '["ใช้สูตร |F∪B∪V| = |F|+|B|+|V|-|F∩B|-|B∩V|-|F∩V|+|F∩B∩V|", "= 70+60+50-20-15-10+5 = 140 คน (ชอบอย่างน้อย 1 ชนิด)", "ไม่ชอบเลย = 150-140 = 10 คน"]', '["ลืมบวกกลับค่าที่ชอบทั้งสามอย่างในสูตร inclusion-exclusion"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-fn-002', 'math1', 'จำนวนและพีชคณิต', 'ฟังก์ชัน', '[]', 'medium', 'ใช้ฟังก์ชันประกอบ (composite function) ในบริบทต้นทุนการผลิต', NULL, 'mc5', 'ปริมาณการผลิตสินค้า (ชิ้น) ของโรงงานเป็นฟังก์ชันของจำนวนคนงาน x คน คือ g(x)=x²-1 และต้นทุนรวม (บาท) เป็นฟังก์ชันของปริมาณผลิต y คือ f(y)=2y+3 ถ้าโรงงานมีคนงาน 3 คน ต้นทุนรวมเท่ากับเท่าใด', '["13 บาท", "16 บาท", "19 บาท", "22 บาท", "25 บาท"]', '19 บาท', '["หาปริมาณผลิตก่อน: g(3)=3²-1=8 ชิ้น", "แทนค่าในฟังก์ชันต้นทุน: f(8)=2(8)+3=19 บาท"]', '["แทนค่า x=3 ลงใน f โดยตรงแทนที่จะหา g(3) ก่อน"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-matrix-002', 'math1', 'จำนวนและพีชคณิต', 'เมทริกซ์', '[]', 'medium', 'ใช้ดีเทอร์มิแนนต์หาเงื่อนไขที่เมทริกซ์ไม่มีตัวผกผัน (singular matrix)', NULL, 'mc5', 'เมทริกซ์ A = [[k, 2], [3, 4]] จะไม่มีตัวผกผัน (A⁻¹ ไม่มีอยู่) เมื่อ k มีค่าเท่าใด', '["0.5", "1.0", "1.5", "2.0", "2.5"]', '1.5', '["เมทริกซ์ไม่มีตัวผกผันเมื่อดีเทอร์มิแนนต์เท่ากับ 0", "det(A) = 4k-6 = 0 → k = 1.5"]', '["คำนวณดีเทอร์มิแนนต์ผิดโดยบวกแทนที่จะลบ (ad-bc)"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-stat-002', 'math1', 'สถิติและความน่าจะเป็น', 'สถิติ', '[]', 'hard', 'คำนวณส่วนเบี่ยงเบนมาตรฐานของประชากร (population standard deviation)', NULL, 'mc5', 'ข้อมูลชุดหนึ่งคือ 2, 4, 4, 4, 5, 5, 7, 9 ส่วนเบี่ยงเบนมาตรฐานของประชากรชุดนี้เท่ากับเท่าใด', '["1", "1.5", "2", "2.5", "3"]', '2', '["ค่าเฉลี่ย = (2+4+4+4+5+5+7+9)/8 = 5", "ผลรวมกำลังสองของส่วนเบี่ยงเบน = 9+1+1+1+0+0+4+16 = 32", "ความแปรปรวน = 32/8 = 4, ส่วนเบี่ยงเบนมาตรฐาน = √4 = 2"]', '["ลืมถอดรากที่สองหลังหาความแปรปรวนแล้ว ตอบความแปรปรวนแทน"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-prob-002', 'math1', 'สถิติและความน่าจะเป็น', 'ความน่าจะเป็น', '[]', 'hard', 'คำนวณความน่าจะเป็นแบบไม่คืนที่ (without replacement)', NULL, 'mc5', 'กล่องใบหนึ่งมีลูกบอลสีแดง 5 ลูก และสีน้ำเงิน 3 ลูก สุ่มหยิบลูกบอลทีละลูกโดยไม่ใส่คืน 2 ครั้ง ความน่าจะเป็นที่จะได้ลูกบอลสีแดงทั้งสองครั้งเท่ากับเท่าใด', '["5/16", "5/14", "5/8", "25/64", "15/56"]', '5/14', '["ครั้งแรกได้แดง: P = 5/8", "ครั้งที่สองได้แดง (ไม่คืนที่ เหลือแดง 4 จาก 7 ลูก): P = 4/7", "P รวม = (5/8)×(4/7) = 20/56 = 5/14"]', '["คำนวณแบบมีการคืนที่ (คูณ 5/8 ซ้ำสองครั้ง) ทั้งที่โจทย์ระบุว่าไม่คืนที่"]');
INSERT OR IGNORE INTO questions (id, subject, section, topic, integrates_with, difficulty, skill_measured, skill_type, format, question, choices, answer, solution_steps, common_mistakes)
VALUES ('math1-calc-002', 'math1', 'แคลคูลัส', 'แคลคูลัสเบื้องต้น', '[]', 'hard', 'ใช้ปริพันธ์หาปริมาณสะสมจากฟังก์ชันอัตรา (integral application)', NULL, 'mc5', 'โรงงานแห่งหนึ่งผลิตสินค้าด้วยอัตรา R(t)=6t² ชิ้นต่อชั่วโมง เมื่อ t คือเวลาเป็นชั่วโมง จำนวนสินค้าทั้งหมดที่ผลิตได้ตั้งแต่ t=0 ถึง t=2 ชั่วโมงเท่ากับกี่ชิ้น', '["8", "12", "16", "20", "24"]', '16', '["ปริมาณสะสม = ∫₀² 6t² dt = [2t³]₀² = 2(2³)-2(0³) = 16 ชิ้น"]', '["ลืมยกกำลัง 3 ตอนหาปฏิยานุพันธ์ของ 6t² (หา 3t² แทน 2t³)"]');
